name: my_little_memory_diary
description: "my_little_memory_diary"

publish_to: "none" 

version: 1.0.11+12

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_storage: ^13.0.1
  cloud_firestore: ^6.0.1
  firebase_cached_image: ^0.10.0
  firebase_messaging: ^16.0.2
  google_sign_in: ^7.2.0
  sign_in_button: ^4.0.1
  table_calendar: ^3.0.9
  flutter_localization: ^0.3.3
  image_picker: ^1.0.7
  extended_image: ^10.0.1
  firebase_crashlytics: ^5.0.1
  dio: ^5.4.1
  google_mobile_ads: ^6.0.0
  upgrader: ^12.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_speed_dial: ^7.0.0
  url_launcher: ^6.2.5
  package_info_plus: ^9.0.0
  home_widget: ^0.8.0
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  path_provider: ^2.1.2
  gal: ^2.3.2

  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.1
  intl: ^0.20.2
  path: ^1.9.1
  flutter_dotenv: ^6.0.0
  collection: ^1.19.1
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - .env
    - images/

  uses-material-design: true
  fonts:
    - family: Nanum
      fonts:
        - asset: fonts/NanumSquareB.otf
        - asset: fonts/NanumSquareEB.otf
        - asset: fonts/NanumSquareL.otf
        - asset: fonts/NanumSquareOTF_acB.otf
        - asset: fonts/NanumSquareOTF_acEB.otf
        - asset: fonts/NanumSquareOTF_acL.otf
        - asset: fonts/NanumSquareOTF_acR.otf
        - asset: fonts/NanumSquareR.otf